### ISSUE TITLE
Cv on git?

### ISSUE THREAD

**Issue by Michael-J-Scofield** [Shadows666/CV#1]
Just wondering why one would create a cv in markdown? 🤔

**Comment by AnnekaSillitoe** [comment]
@Michael-J-Scofield my bootcamp told me to when I was there, so that's what I did.

**Comment by Michael-J-Scofield** [comment]
Alright, one more thing. please scale the images on your portfolio. Page size is now 25 or something mb lol

**Comment by AnnekaSillitoe** [comment]
I'm in the process of building a new one as this one is incredibly out of date. So actually I could probably just remove the link, but thanks @Michael-J-Scofield
